[package]
name = "tabut"
version = "0.0.1"
authors = ["Amelia Mowers <https://github.com/Amelia-Mowers>"]
license = "MIT"
description = "Display data as tables."
entrypoint = "lib.typ"
repository = "https://github.com/Amelia-Mowers/tabut"
keywords = ["formatting", "table", "tables", "data", "display"]